name: pyautoenv test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "uv.lock"
          enable-cache: true
          python-version: "3.9"
          version: "0.6.13"
      - name: Install pyautoenv
        run: uv sync --all-groups
      - name: Code Quality
        run: |
          uv run pre-commit run --all-files
      - name: Test
        run: |
          uv run pytest --cov --cov-report=term-missing --cov-report=xml --benchmark-disable
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-windows:
    name: Test-Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "uv.lock"
          enable-cache: true
          python-version: "3.9"
          version: "0.6.13"
      - name: Install pyautoenv
        run: uv sync --all-groups
      - name: Test
        run: |
          uv run pytest --cov --cov-report=term-missing --benchmark-disable
