name: py-autoenv test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Code Quality
      run: |
        python -m pip install pre-commit
        pre-commit run --all-files
    - name: Test
      run: |
        python -m pip install poetry
        poetry install --with=test
        poetry run pytest --cov --cov-report=term-missing
